### ISSUE TITLE
Cascadia is not compatible with Visual Studio 2019 Professional

### ISSUE THREAD

**Issue by dmitryrusak** [microsoft/cascadia-code#218]
When selected Cascadia, the Visual Studio just uses the Courier New font. 
Tested on:
Visual Studio Professional 2019
Version 16.3.9

**Comment by zunderscore** [comment]
I'm on Visual Studio Pro 2019 16.4.2 and cannot repro this. Have you updated to the latest version of VS and is this still an issue?

**Comment by zunderscore** [comment]
Hey @dmitryrusak, is this still an issue?

**Comment by dmitryrusak** [comment]
hi Zack,
i have re-installed the Cascadia and Cascadia Mono (latest 1911.21).
First i selected the Cascadia Mono in my VS2019 and it crashed the VS. 
Here is a stack:
*************************************************
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32)
   at MS.Internal.Text.TextInterface.Font.CreateFontFace()
   at MS.Internal.Text.TextInterface.Font.AddFontFaceToCache()
   at MS.Internal.Text.TextInterface.Font.GetFontFace()
   at System.Windows.Media.GlyphTypeface..ctor(MS.Internal.Text.TextInterface.Font)
   at MS.Internal.FontFace.PhysicalFontFamily.GetGlyphTypeface(System.Windows.FontStyle, System.Windows.FontWeight, System.Windows.FontStretch)
   at MS.Internal.FontFace.PhysicalFontFamily.MS.Internal.FontFace.IFontFamily.GetTypefaceMetrics(System.Windows.FontStyle, System.Windows.FontWeight, System.Windows.FontStretch)
   at System.Windows.Media.Typeface.ConstructCachedTypeface()
   at System.Windows.Media.Typeface.get_CachedTypeface()
   at System.Windows.Media.Typeface.CheckFastPathNominalGlyphs(System.Windows.Media.TextFormatting.CharacterBufferRange, Double, Single, Double, Double, Boolean, Boolean, System.Globalization.CultureInfo, System.Windows.Media.TextFormattingMode, Boolean, Boolean, Int32 ByRef)
   at MS.Internal.TextFormatting.SimpleRun.CreateSimpleTextRun(System.Windows.Media.TextFormatting.CharacterBufferRange, System.Windows.Media.TextFormatting.TextRun, MS.Internal.TextFormatting.TextFormatterImp, Int32, Boolean, Boolean, Double)
   at MS.Internal.TextFormatting.SimpleRun.Create(MS.Internal.TextFormatting.FormatSettings, System.Windows.Media.TextFormatting.CharacterBufferRange, System.Windows.Media.TextFormatting.TextRun, Int32, Int32, Int32, Int32, Int32, Double)
   at MS.Internal.TextFormatting.SimpleTextLine.Create(MS.Internal.TextFormatting.FormatSettings, Int32, Int32, Double)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLineInternal(System.Windows.Media.TextFormatting.TextSource, Int32, Int32, Double, System.Windows.Media.TextFormatting.TextParagraphProperties, System.Windows.Media.TextFormatting.TextLineBreak, System.Windows.Media.TextFormatting.TextRunCache)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLine(System.Windows.Media.TextFormatting.TextSource, Int32, Double, System.Windows.Media.TextFormatting.TextParagraphProperties, System.Windows.Media.TextFormatting.TextLineBreak)
   at System.Windows.Media.FormattedText+LineEnumerator.FormatLine(System.Windows.Media.TextFormatting.TextSource, Int32, Double, System.Windows.Media.TextFormatting.TextParagraphProperties, System.Windows.Media.TextFormatting.TextLineBreak)
   at System.Windows.Media.FormattedText+LineEnumerator.MoveNext()
   at System.Windows.Media.FormattedText.DrawAndCalculateMetrics(System.Windows.Media.DrawingContext, System.Windows.Point, Boolean)
   at System.Windows.Media.FormattedText.get_Metrics()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.TextInfoCache.GetTextInfo(System.Windows.Media.TextFormatting.TextRunProperties)
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedTextSourceFactoryService.Create(Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.ITextSnapshot, Int32, Double, Double, Double, Boolean, Microsoft.VisualStudio.Text.Classification.IClassifier, Microsoft.VisualStudio.Text.Formatting.ITextAndAdornmentSequencer, Microsoft.VisualStudio.Text.Classification.IClassificationFormatMap, Boolean)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PreLayout(LayoutLineCache)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout(Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.SnapshotPoint, Double, Microsoft.VisualStudio.Text.Editor.ViewRelativePosition, Double, Double, Boolean, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout(Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.ITextSnapshot)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.<QueueLayout>b__270_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
*****************************
However after re-starting the VS the font is working. 
Still, its not reacting on "Bold" selection checkbox (bold or non-bold are the same)
Cascadia and Cascadia Mono look the same

My Visual Studio:
Microsoft Visual Studio Professional 2019
Version 16.3.9
VisualStudio.16.Release/16.3.9+29509.3
Microsoft .NET Framework
Version 4.7.03190

**Comment by rockerviktor** [comment]
You just have to restart Visual Studio after you change the font.

**Comment by aaronbell** [comment]
> Still, its not reacting on "Bold" selection checkbox (bold or non-bold are the same)
Cascadia and Cascadia Mono look the same

The bold selection will not work as expected as there is no Bold weight for either Cascadia Code, nor Cascadia Mono. So no problems there. 

The difference between Cascadia Code and Cascadia Mono is the support of coding ligatures. Code has them, Mono does not. Otherwise they are identical. 

Anyway, seems like this issue has been resolved. Closing! :)
